config/routes.rb
Domi01::Application.routes.draw do
  get "users/new"
  root to: "pages#home"

  get "/auth/:provider/callback" => "sessions#create", via: [:get, :post]
  get "/signout" => "sessions#destroy", :as => :signout

  match '/help', to: 'pages#help', via: 'get'
  match '/team', to: 'pages#team', via: 'get'
  match 'about', to: 'pages#about', via: 'get'
  match 'contact', to: 'pages#contact', via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	def self.create_with_omniauth(auth)
	  create! do |user|
	    user.provider = auth["provider"]
	    user.uid = auth["uid"]
	    user.name = auth["info"]["name"]
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def team
  end

  def about
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
	  auth = request.env["omniauth.auth"]
	  user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
	  session[:user_id] = user.id
	  redirect_to root_url, :notice => "Signed in!"
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, :notice => "Signed out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Domi</a>
    made with love
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Domi", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <% if current_user %>
                Welcome <%= current_user.name %>!
                <li><%= link_to "Sign Out", signout_path %></li>
              <% else %>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Help", help_path %></li>
                <li><%= link_to "Sign in with Facebook", "/auth/facebook" %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Domi</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<html>
<head>
	<title>Domi: College housing made easy</title>
</head>
<body>
	<h1>About us</h1>
	<p>
		Domi was born out the frustration of one of our co-founders on how terrible his experience was in getting housing. Funny - or rather not - enough another co-founder had an even worse experience where someone backed out of the agreed rent. So finally they quit b*tching, got some other guys, and built this tool to make sure that neve happens again. 
	</p>
</body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<html>
<head>
	<title>Domi: College housing made easy</title>
</head>
<body>
	<h1>Help</h1>
	<p>
		If you have any questions please do not hesitate to contact
		<a href="mailto:madeleke13@gmail.com">Me</a>
		and we will chat as soon as possible. 
	</p>
</body>
</html>

app/views/pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Domi</h1>

  <h2>
  	We are making college housing ridiculously easy. <br>
    College Housing - Agony = Domi
  </h2>


  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

app/views/pages/team.html.erb
<h1>Our Team</h1>
<p>
	This is a band of hackers looking to disrupt the college housing industry.
</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>